// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJ-dAe9y8R2yuAD_5kmF2duZaHJ-eEQw',
    appId: '1:744875365999:web:5ee583a491e3d4d0041f9a',
    messagingSenderId: '744875365999',
    projectId: 'moneytracker-6affa',
    authDomain: 'moneytracker-6affa.firebaseapp.com',
    storageBucket: 'moneytracker-6affa.appspot.com',
    measurementId: 'G-NNQS6Y14TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEh3XuPwnz5Z8lkSO_UTuxGYaW_-1ylU',
    appId: '1:744875365999:android:c875d793d1128569041f9a',
    messagingSenderId: '744875365999',
    projectId: 'moneytracker-6affa',
    storageBucket: 'moneytracker-6affa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2lve2HuqS-F2CAO78VrFR4XiPxz9Iwk',
    appId: '1:744875365999:ios:ba6892a7b8928ea8041f9a',
    messagingSenderId: '744875365999',
    projectId: 'moneytracker-6affa',
    storageBucket: 'moneytracker-6affa.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF2lve2HuqS-F2CAO78VrFR4XiPxz9Iwk',
    appId: '1:744875365999:ios:ba6892a7b8928ea8041f9a',
    messagingSenderId: '744875365999',
    projectId: 'moneytracker-6affa',
    storageBucket: 'moneytracker-6affa.appspot.com',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQJ-dAe9y8R2yuAD_5kmF2duZaHJ-eEQw',
    appId: '1:744875365999:web:e8dc496d6e9ac8f1041f9a',
    messagingSenderId: '744875365999',
    projectId: 'moneytracker-6affa',
    authDomain: 'moneytracker-6affa.firebaseapp.com',
    storageBucket: 'moneytracker-6affa.appspot.com',
    measurementId: 'G-J01WW2R4SH',
  );
}
