// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTAWEuz1EB7E6uEj7LmRqBSSFmjDRHfk',
    appId: '1:1053941365696:web:f63e0703568597ddfc2625',
    messagingSenderId: '1053941365696',
    projectId: 'financeflow-378d7',
    authDomain: 'financeflow-378d7.firebaseapp.com',
    storageBucket: 'financeflow-378d7.appspot.com',
    measurementId: 'G-H14G1NT5EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1OqjhcopCuF3daFdA6gQ5cgway8-NZ9s',
    appId: '1:1053941365696:android:c352e2818308b1d3fc2625',
    messagingSenderId: '1053941365696',
    projectId: 'financeflow-378d7',
    storageBucket: 'financeflow-378d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN6a29X1A46PofoE6hH6lIIlwp7GIqFa8',
    appId: '1:1053941365696:ios:4f6220f9b6fcc538fc2625',
    messagingSenderId: '1053941365696',
    projectId: 'financeflow-378d7',
    storageBucket: 'financeflow-378d7.appspot.com',
    iosBundleId: 'com.example.moneytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN6a29X1A46PofoE6hH6lIIlwp7GIqFa8',
    appId: '1:1053941365696:ios:4f6220f9b6fcc538fc2625',
    messagingSenderId: '1053941365696',
    projectId: 'financeflow-378d7',
    storageBucket: 'financeflow-378d7.appspot.com',
    iosBundleId: 'com.example.moneytracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKTAWEuz1EB7E6uEj7LmRqBSSFmjDRHfk',
    appId: '1:1053941365696:web:2cadc87f19e2ad6dfc2625',
    messagingSenderId: '1053941365696',
    projectId: 'financeflow-378d7',
    authDomain: 'financeflow-378d7.firebaseapp.com',
    storageBucket: 'financeflow-378d7.appspot.com',
    measurementId: 'G-GHYEQJXESR',
  );

}