import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Add this import for Firebase
import 'package:moneytracker/common/color_extension.dart';
import 'package:moneytracker/view/lets_get_Started/SplashPage.dart';
import 'package:moneytracker/view/login/welcome_view.dart';
import 'package:moneytracker/view/main_tab/main_tab_view.dart';
import 'firebase_options.dart'; // This file is autogenerated by Firebase CLI

void main() async {
  // Ensure that Firebase is initialized before the app runs
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions
        .currentPlatform, // Initialize Firebase with platform-specific options
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Trackizer',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: "Inter",
        colorScheme: ColorScheme.fromSeed(
          seedColor: TColor.primary,
          background: TColor.gray80,
          primary: TColor.primary,
          primaryContainer: TColor.gray60,
          secondary: TColor.secondary,
        ),
        useMaterial3: false,
      ),
      home: const MainTabView(),
    );
  }
}
